// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efzwiecsruzsehxiqizc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmendpZWNzcnV6c2VoeGlxaXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzcwMzUsImV4cCI6MjA3MjA1MzAzNX0.daz5YTMfGYyNGKAqYxTGiH3Pz4Q-o2E8o9Y6SHnXi8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});